"""邮件通知模块 — SMTP 发送测试报告"""

import logging
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders
from datetime import datetime
from typing import Optional

from backend.config import settings

logger = logging.getLogger("testforge")


def is_email_configured() -> bool:
    """检查 SMTP 邮件是否已配置"""
    return bool(settings.smtp_host and settings.smtp_user and settings.smtp_password)


def send_test_report_email(
    to_emails: list[str],
    api_title: str,
    execution: dict,
    pdf_bytes: Optional[bytes] = None,
    scan_url: str = "",
) -> dict:
    """发送测试报告邮件

    Args:
        to_emails: 收件人邮箱列表
        api_title: API 名称
        execution: 执行结果
        pdf_bytes: PDF 附件内容（可选）
        scan_url: 扫描的 URL

    Returns:
        {"success": bool, "error": str, "message_id": str}
    """
    if not is_email_configured():
        return {
            "success": False,
            "error": "SMTP 未配置，请在 .env 中设置 TESTFORGE_SMTP_HOST/USER/PASSWORD",
        }

    total = execution.get("total", 0)
    passed = execution.get("passed", 0)
    failed = execution.get("failed", 0)
    pass_rate = round(passed / total * 100, 1) if total else 0
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    # 构建邮件
    msg = MIMEMultipart()
    msg["From"] = settings.smtp_user
    msg["To"] = ", ".join(to_emails)
    status_emoji = "✅" if failed == 0 else "⚠️"
    msg["Subject"] = f"{status_emoji} TestForge 测试报告 — {api_title} ({passed}/{total} 通过)"

    # HTML 邮件正文
    fail_color = "#dc2626" if failed > 0 else "#16a34a"
    html_body = f"""
    <html><body style="font-family: -apple-system, Arial, sans-serif; background: #f8fafc; padding: 20px;">
    <div style="max-width: 600px; margin: 0 auto; background: white; border-radius: 12px; overflow: hidden; box-shadow: 0 1px 3px rgba(0,0,0,0.1);">

        <!-- 头部 -->
        <div style="background: #0f172a; padding: 24px 32px;">
            <h1 style="color: #38bdf8; margin: 0; font-size: 22px;">⚒️ TestForge 测试报告</h1>
            <p style="color: #64748b; margin: 8px 0 0; font-size: 13px;">{now}</p>
        </div>

        <!-- API 信息 -->
        <div style="padding: 24px 32px;">
            <h2 style="color: #1e293b; font-size: 18px; margin: 0 0 12px;">📋 {api_title}</h2>
            {f'<p style="color: #64748b; font-size: 13px;">扫描目标: <a href="{scan_url}" style="color:#3b82f6;">{scan_url}</a></p>' if scan_url else ''}

            <!-- 统计卡片 -->
            <div style="display: flex; gap: 12px; margin: 20px 0;">
                <div style="flex:1; background: #f1f5f9; border-radius: 8px; padding: 16px; text-align: center;">
                    <div style="font-size: 28px; font-weight: 800; color: #1e293b;">{total}</div>
                    <div style="color: #64748b; font-size: 12px;">总测试</div>
                </div>
                <div style="flex:1; background: #dcfce7; border-radius: 8px; padding: 16px; text-align: center;">
                    <div style="font-size: 28px; font-weight: 800; color: #16a34a;">{passed}</div>
                    <div style="color: #16a34a; font-size: 12px;">通过</div>
                </div>
                <div style="flex:1; background: #fef2f2; border-radius: 8px; padding: 16px; text-align: center;">
                    <div style="font-size: 28px; font-weight: 800; color: {fail_color};">{failed}</div>
                    <div style="color: {fail_color}; font-size: 12px;">失败</div>
                </div>
                <div style="flex:1; background: #dbeafe; border-radius: 8px; padding: 16px; text-align: center;">
                    <div style="font-size: 28px; font-weight: 800; color: #3b82f6;">{pass_rate}%</div>
                    <div style="color: #3b82f6; font-size: 12px;">通过率</div>
                </div>
            </div>

            <!-- 结论 -->
            <div style="background: {'#dcfce7' if failed == 0 else '#fef3c7'}; border-radius: 8px; padding: 16px; margin-top: 16px;">
                <p style="margin: 0; color: {'#16a34a' if failed == 0 else '#92400e'}; font-size: 14px;">
                    {'✅ 全部测试通过！' if failed == 0 else f'⚠️ {failed} 个测试失败，请检查下方详情'}
                </p>
            </div>

            {'<p style="color: #64748b; font-size: 13px; margin-top: 16px;">📎 详细 PDF 报告已附在邮件中。</p>' if pdf_bytes else ''}
        </div>

        <!-- 页脚 -->
        <div style="background: #f1f5f9; padding: 16px 32px; text-align: center;">
            <p style="color: #94a3b8; font-size: 12px; margin: 0;">
                Generated by TestForge — 智能测试平台
            </p>
        </div>
    </div>
    </body></html>
    """
    msg.attach(MIMEText(html_body, "html", "utf-8"))

    # 附加 PDF
    if pdf_bytes:
        attachment = MIMEBase("application", "pdf")
        attachment.set_payload(pdf_bytes)
        encoders.encode_base64(attachment)
        attachment.add_header(
            "Content-Disposition",
            "attachment",
            filename=f"testforge_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf",
        )
        msg.attach(attachment)

    # 发送
    try:
        port = settings.smtp_port
        if settings.smtp_use_tls:
            server = smtplib.SMTP_SSL(settings.smtp_host, port, timeout=30)
        else:
            server = smtplib.SMTP(settings.smtp_host, port, timeout=30)
            server.starttls()

        server.login(settings.smtp_user, settings.smtp_password)
        server.sendmail(settings.smtp_user, to_emails, msg.as_string())
        server.quit()

        logger.info("测试报告邮件已发送至 %s", to_emails)
        return {"success": True, "error": "", "recipients": to_emails}

    except Exception as e:
        logger.error("邮件发送失败: %s", e)
        return {"success": False, "error": str(e)}
